---
title: "Project 1: Accelerating the Energy Transition"
date: 2024-09-05
module: 1

categories: [Project]
format: html
---

The Energy Transition is a rapidly accelerating global trend that promises tremendous social, economic, and environmental benefits but that also poses significant challenges.
A plethora of technological, policy, and business model innovations are being developed to facilitate the transition to a more sustainable energy system.
A key challenge for observers and decision-makers is to separate the hype from the reality and to identify the most promising pathways to a sustainable energy future.

In this project, you will sign research a specific proposed solution to the energy transition and evaluate its potential to contribute to a sustainable energy future.
You will first find a promising solution to research: -- good places to start are interviews with founders from podcasts such as [Volts](https://www.volts.wtf/), [Catalyst](https://www.canarymedia.com/podcasts/catalyst-with-shayle-kann), or [Cleaning Up](https://www.cleaningup.live/).
You will then provide a critical assessment of the solution, relying on more balanced and nuanced sources.
Critical questions to answer are the following:

- What is the specific problem for which the proposed solution is intended? How does it relate to broader (and harder to pin down) goals?
- What external factors (e.g., abundant clean electricity?) are necessary for the solution to succeed?
- In a best-case scenario, how much impact could the solution have on global climate?
- What are the main technical, economic, and policy impediments to the solution's success?

You will work in small groups and submit a written report and develop an in-class presentation.

## Timeline

- [ ] Thursday, Sep 5: Project assigned
- [ ] Tuesday, Sep 10: Choose one topic / podcast episode that seems interesting, listen to or read the episode, and write a one-pager (individual)
- [ ] Thursday, Sep 12: Groups formed. Each group member should listen to the podcast episode chosen by group members and read the one-pager written by group members.
- [ ] Thursday, Sep 19: Select a topic and collectively draft a one-pager (group)
- [ ] Thursday, Oct 1: Group written report due on Canvas
- [ ] Thursday, Oct 3: Presentations in class

## One-pager

The one-pager should be submitted on Canvas and should include your name, the name of your solution, your primary source, and short answers to the questions indivated above.
Save as a PDF and submit on Canvas.

## Report

A detailed report should be 3-5 pages long, should reference at least 3 highly reputable sources beyond the podcast you listened to, and should address the questions above in a thoughtful manner.
We will provide a template for the report, including instructions on how to format your report, including references and a rubric.
Save as a PDF and submit on Canvas.

## Presentation

This is a large class.
Each group will present a 5 minute presentation on their proposed solution.
Each group member should present, and groups will be graded on the quality of the presentation rather than the quality of the content (which will be evaluated based on the report).
