---
title: "Fixing bugs for extra credit"
format: html
---

You can get extra credit if you find and/or fix any bug (major or minor) in the course materials.
Here's how.

1. **Find a bug**. This could be a typo, a broken link, a mistake in the code, or anything else that you think is wrong.
2. **Create an issue**. Go to the [course GitHub repository](https://ceve-421-521.github.io/ceve-421-521.github.io) and click on the "Issues" tab. Click the "New issue" button and describe the bug you found. This description can be very short (e.g., "typo in lecture 3 slide 5"). This is worth 1 point.
    1. Optionally, identify the specific line in the source code where the bug occurs. To link to the line, clikc on the line number, then click "Copy permalink". Include this in the Issue. This is worth another point.
3. **Fix the bug**. If you know how to fix the bug, you can do so.
    1. There are two ways to create a pull request:
        1. **On GitHub**: Click the "Edit" button on the page where the typo occurs. Make the change, then click "Propose changes". This is worth 1 point.
        1. **On your computer**: First, [**fork**](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/fork-a-repo) the course repository. Then, **clone** your fork to your computer. Make the change in your local copy, then **commit** and **push** the change to your fork. Finally, create a **pull request** to merge your change into the main course repository. This is worth 1 points.
    1. In either case: include the issue number in your commit message. For example, `Resolves #10,` for a fix that solves issue #10. That way, when the change is merged, the issue will be automatically closed.

If you're stuck, check out [this 5 minute walkthrough](https://www.youtube.com/watch?v=rgbCcBNZcdQ) of the process.
Or ask for help!

At the end of the semester, you'll get points based on the "bug points" you gathered over the semester.
I'll weight so that everyone who found even one bug gets one point of extra credit and the person who found the most bugs gets 5 points of extra credit.