---
format:
  html:
    toc-depth: 3
    title: Syllabus
  pdf:
    documentclass: article
    fontsize: 11pt
    geometry:
      - margin=1in  
    include-in-header:
      text: |
        \renewcommand\toprule[2]\relax
        \renewcommand\bottomrule[2]\relax
    title: "{{< var course.number >}} ({{< var course.title >}}) Syllabus"
    subtitle: "{{< var course.semester >}}"

listing:
  type: table
  contents:
    - "lectures/*.qmd"
  sort:
    - "date"
    - "title"
  table-striped: true
  table-hover: true
  categories: numbered
  fields: [module, title, date]
  field-display-names: 
    module: "Module"
    title: "Topic"
    date: "Date"
  page-size: 100
  id: listing-lectures
---

:::: {.content-visible unless-format="html"}

::: {.callout-important}
An interactive, updated divital version of this syllabus is posted online at [{{< var course.url >}}]({{< var course.url >}}/syllabus).
:::

## Course Description

Civil and Environmental Engineers (CEVEs) engage in the planning, design, construction, operation, retrofit, demolition, and reuse of infrastructure systems that form the backbone of societies and economies.
CEVEs work at the dynamic interface of the built environment, information environment, and natural environment on topics like smart cities and construction, sustainable energy and buildings, connected and automated transportation systems, resilient infrastructure, climate change mitigation and adaptation, and water management.
In this course, students will explore how data science, environmental science, economic analysis,  structural design, and systems thinking can be integrated to promote sustainability, resilience, and equity.
Through a mix of technical lectures, topical seminars on applications and ideas of interest, and team-based projects, students will develop skills in data analysis, system modeling, and engineering design and develop an understanding of the broad field of civil and environmental engineering and its applications.

::::

## Course Information
:::: {.columns .course-details}

::: {.column width="30%"}
### Instructor

* {{< fa user title="Name" >}} [[{{< var instructor.name_no_title >}}]({{< var instructor.url >}})]{.ms-1}
* {{< fa envelope title="Email" >}} [[{{< var instructor.email >}}](mailto:{{< var instructor.email >}})]{.ms-1}
* {{< fa building title="Office" >}} [{{< var instructor.office >}}]{.ms-2}
:::

::: {.column width="30%"}
### Grader

TBD
::::

::: {.column width="30%"}
### Meetings

* {{< fa calendar title="Class Days" >}} {{< var course.days >}}
* {{< fa clock title="Class Time" >}} {{< var course.time >}}
* {{< fa university title="Class Location" >}} {{< var course.location >}}
:::

::::

### Prerequisites

None.
All interested students are warmly invited to participate!

### Course Objectives 

This course is intended to introduce you to the discipline of civil and environmental engineering through examination of topics in energy systems, water systems, urban mobility, and coastal resilience.
This course emphasizes analytical skills, systems thinking, communication, and teamwork.


On completing this course, students should be able to:

1. Identify and understand the interconnections between various civil and environmental engineering subfields, and explore potential career paths within these areas, including their requirements and societal impacts.
1. Apply fundamental principles and approaches in CEVE disciplines to solve engineering problems, utilizing knowledge from other first-year courses such as calculus and physics.
1. Generate high-quality engineering calculations, analyses, and reports, demonstrating proficiency in technical communication through both written work and oral presentations.
1. Collaborate effectively in project teams, including peer evaluation, constructive feedback, and collective problem-solving. Develop skills in managing group dynamics, delegating tasks, and integrating diverse perspectives to achieve project goals.
1. Understand the scope and impact of civil and environmental engineering in addressing global challenges, particularly in relation to sustainability, resilience, and equity. Recognize the interdisciplinary nature of the field and its connections to other areas of study and societal issues.
1. Critically evaluate the ethical implications of engineering decisions, considering their impact on society, the environment, and future generations.

### Required Materials

No textbook is required for this course.
All materials will be posted as open source on [the course website]({{< var course.url >}}) or on [Canvas](https://canvas.rice.edu/courses/{{< var course.canvas_id >}}).

You will occasionally be assigned scientific papers to read.
Where those are available through the Rice library, you will be expected to access them yourself.
You are encouraged, though not required, to use Zotero (Rice students have free storage).
See [Fondren Library's Resources](http://fondrenlearning.blogs.rice.edu/zotero/) for resources.

## A Community of Learning

Rice's [core values](https://www.rice.edu/mission-values) are responsibility, integrity, community, and excellence.
Our goal is to create a learning community aligned with these core values.

### Core Expectations

Course success involves a dual responsibility on the part of the instructor and the student.

:::: {.columns}

::: {.column width="48%"}
As the instructor, my responsibility is to provide you with a structure and opportunity to learn.
To this end, I commit to:

* provide organized and focused lectures, in-class activities, and assignments;
* encourage students to regularly evaluate and provide feedback on the course;
* manage the classroom atmosphere to promote learning;
* schedule sufficient out-of-class contact opportunities, such as office hours;
* allow adequate time for assignment completion;
* make lecture materials, class policies, activities, and assignments accessible to students. 
:::

::: {.column width="4%"}
:::

::: {.column width="48%"}
Students are responsible for their own learning in the course and should commit to:

* attending all lectures;
* doing all required preparatory work before class; 
* actively participating in online and in-class discussions;
* beginning assignments and other work early; and
* attending office hours as needed. 
:::
::::

### Diversity, Equity, and Inclusion

Rice is committed to building and maintaining an equitable and inclusive campus community.
Diversity can refer to multiple ways that we identify ourselves, including but not limited to race, color, national origin, language, sex, disability, age, sexual orientation, gender identity, religion, creed, ancestry, belief, veteran status, or genetic information.
Each of these diverse identities, along with many others not mentioned here, shape the perspectives our students, faculty, and staff bring to our campus.
We, at Rice, will work to promote diversity, equity and inclusion not only because diversity fuels excellence and innovation, but because we want to pursue justice.
We acknowledge our imperfections while we also fully commit to the work, inside and outside of our classrooms, of building and sustaining a campus community that increasingly embraces these core values.

Each of us is responsible for creating a safer, more inclusive environment.

### Accommodation for Students with Disabilities

If you have a documented disability or other condition that may affect academic performance you should: 1) make sure this documentation is on file with the Disability Resource Center (Allen Center, Room 111 / [adarice@rice.edu](mailto:adarice@rice.edu) / x5841) to determine the accommodations you need; and 2) talk with me to discuss your accommodation needs.

### Accommodation for Scheduling Conflicts

If any of our class meetings conflict with your religious events, student athletics, or other non-negotiable scheduling conflict, please let me know ASAP so that we can make arrangements for you.


### Getting Help

You can ask questions through Canvas Discussions and Office Hours.
We will make an effort to respond to all Canvas discussion questions within 24 hours, though this won't always be possible (travel, weekends, etc.).
Please do not use email for questions about course content or labs, since other students may have related questions.
You *should* use email for questions about personal matters, such as scheduling conflicts, accommodations, etc.

## Academic Integrity

This class is designed to encourage collaboration, and students are encouraged to discuss their work with other students.
Engineering as a profession relies upon the honesty and integrity of its practitioners (see *e.g.* the [American Society for Civil Engineers' Code of Ethics](https://www.asce.org/-/media/asce-images-and-files/career-and-growth/ethics/documents/asce-code-ethics.pdf)).
**All work submitted must represent the students' own work and understanding**, whether individually or as a group (depending on the particulars of the assignment).

If you are ever unclear about academic integrity, please ask!
Additionally, always err on the side of providing more information.)

### Rice Honor Code

More specifically, all students will be held to the standards of the Rice Honor Code, a code that you pledged to honor when you matriculated at this institution.
If you are unfamiliar with the details of this code and how it is administered, you should consult the Honor System Handbook at [honor.rice.edu/honor-system-handbook/](https://honor.rice.edu/honor-system-handbook/).
This handbook outlines the University's expectations for the integrity of your academic work, the procedures for resolving alleged violations of those expectations, and the rights and responsibilities of students and faculty members throughout the process.

### AI/ML Resource Policy {#sec-llm}

Large language models (LLMs), like GPT, are powerful tools for generating text that can be used for coding and doing data analysis.
This is at once empowering (LLMs are powerful and can save you time) and risky (LLMs can make mistakes that are hard to detect).

Our general view is that LLMs are powerful tools that you will encounter and use when you leave this classroom, so it's important to learn how to use them responsibly and effectively.
You are generally permitted to use LLMs in this course, but ultimately, you are responsible for guaranteeing, understanding, and interpreting your results.
In particular:

- One of the best applications of LLMs is to write code. This can help accelerate your workflow, especially when you are learning new syntax. However, LLMs can make bad decisions about how to structure your code, can introduce bugs, and can mislead you about what your code is doing. You are responsible for understanding and debugging your code, and for ensuring that it does what you intend it to do.
- LLMs should not be used to generate text that you submit as your own work. If you are assigned a writing assignment, the point is to stimulate your thought process, and you short-cut this if you ask a LLM to generate the response for you. This leads to shallow thinking! However, you *may* use tools including LLMs (but also Grammarly, spell-check, etc.) to help you edit your writing. This can sometimes be a fine line; it's always better to ask if you're not sure, and to disclose your use of these tools in your submission

### Policy on Web Posting of Course Materials

Uploading course materials to web sites is not an authorized use of the course material.
Both the poster and the user are in violation of the university policy, which is actionable.

## Grading

There are two components to your grade in this course: participation and projects. Participation forms 40% of your grade and projects form 60% of your grade. The course will be split into four modules, each weighted equally (10 points for participation and 15 for a project).

### Participation

Participation is essential to this course.
To earn full points for participation, you should do assigned readings, attend class, share your thoughts in class, and participate in group work.
You will be provided with multiple ways to share your thoughts in class beyond raising your hand and speaking.
All readings will be posted in advance and announced in class.
I reserve the right to give pop quizzes on the readings, so be prepared!

Participation will be assessed for each module, and both students and I will provide feedback.
Your lowest module participation grade will be dropped.

### Projects

Each module of the course will culminate in a group design project.
Specific instructions and a detailed rubric will be provided for each project at the time of assignment.
These rubrics will outline the expectations for the project and how it will be evaluated.

Group work will be assessed through a combination of the final product and peer evaluations.
Each team member will confidentially evaluate their peers' contributions, which will factor into individual grades for group projects.

Late projects will be subjected to a 10% penalty per day.

## Preliminary Schedule

The following schedule outlines our planned topics and readings for the semester.

::: {.callout-note}
This **preliminary schedule** is subject to change during the semester and **will change before the start of the semester.**
Updated versions will be posted on [the Schedule page](./schedule.qmd) of the course website.
:::


::: {#listing-lectures}
:::
